[workspace]
preview = ["pixi-build"]
channels = ["conda-forge"]
platforms = ["linux-64", "osx-arm64", "osx-64", "win-64"]

[package]
name = "asetools"
version = "0.1"

[package.build]
backend = { name = "pixi-build-python", version = "*" }

[package.host-dependencies]
setuptools = ">=61.0"
wheel = "*"

[package.run-dependencies]
pandas = "*"
matplotlib = "*"
numpy = "*"
scipy = "*"
ase = "*"
pyyaml = "*"

[dependencies]
asetools = { path = "." }